### ISSUE TITLE
Display Job Listings

### ISSUE THREAD

**Issue by gabriellamingozzi** [CS320F21T3/hiring-hand#3]

**Comment by benmelz** [comment]
Discuss:
- [ ] Database schema for the `Listing` model
- [ ] Relationship with other tables in database

Server Tasks:
- [ ] `listings` table
- [ ] `listings` seeds
- [ ] `Listing` model
- [ ] `listingsController` (needs `index` endpoint at minimum)

Client Tasks:
...
